name: PR Labelername: PR Labeler



on:on:

  pull_request_target:  pull_request_target:

    types: [opened, synchronize, reopened, edited, ready_for_review]    types: [opened, synchronize, reopened, edited, ready_for_review]



permissions:permissions:

  contents: read  contents: read

  pull-requests: write  pull-requests: write



jobs:jobs:

  label:  label:

    runs-on: ubuntu-latest    runs-on: ubuntu-latest

    steps:    steps:

      - uses: actions/labeler@v5      - uses: actions/labeler@v5

        with:        with:

          repo-token: ${{ secrets.GITHUB_TOKEN }}          repo-token: ${{ secrets.GITHUB_TOKEN }}

          configuration-path: .github/labeler.yml          configuration-path: .github/labeler.yml

          sync-labels: true          sync-labels: true
